### ISSUE TITLE
Chatルームを切り替えた時に画面のスクロール位置が変わらないようにしたい

### ISSUE THREAD

**Issue by fukajun** [pandeiro245/245cloud#108]
おおよそ表題の内容ですが、たまに切り替わる時が有ります。

**Comment by pandeiro245** [comment]
@fukajun うーん、今確かめてみたのですが
件数が少ない部屋を見ている状態で件数が多い部屋をクリックすると
縦スクロール幅が広がって切り替わるみたいですね。

これってどう対応したらいいでしょう。

部屋選択を`posisition: fixed;`で固定にするとか？？
