### ISSUE TITLE
pomoが自動スタートするURLパラメータ

### ISSUE THREAD

**Issue by tektoh** [pandeiro245/245cloud#113]
[コマンドライン](https://github.com/tektoh/pomo)からpomoを始めたい

* [x] とりあえず実装
* [ ] DONEが表示される前にstartが実行されてしまい、その後にDONEがレンダリングされてそのまま残るバグを修正

**Comment by pandeiro245** [comment]
@tektoh 下記にて本番反映しました！
https://github.com/pandeiro245/245cloud/pull/133

**Comment by pandeiro245** [comment]
@tektoh 

bashrcに
`alias stayhungry='open "http://245cloud.com/?auto_start=1&auto_close=1#soundcloud:25382260"'`
って書いたら
stayhungryでauto_play始まって楽しいｗ

**Comment by pandeiro245** [comment]
「DONEが表示される前にstartが実行されてしまい、その後にDONEがレンダリングされてそのまま残る」という現象が発生してるけど
よく考えたらこうじゃないとDONEが見える機会ないからこれはこれでいいかも？

**Comment by tektoh** [comment]
pomoコマンドを自動スタートに対応しました〜w
https://github.com/tektoh/pomo/pull/1

pomo 245cloud で stayhungry が始まる

**Comment by pandeiro245** [comment]
@tektoh おおお、動きました！１つissue追加させて頂きました。
https://github.com/tektoh/pomo/issues/2
これができるとアツイｗ
