### ISSUE TITLE
【要検討】parse.comを廃止してmysql化

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#136]
* [x] 主要部分のParse.com廃止
* [ ] 副次部分（Ad, Accesslog, Music）のParse.com廃止

**Comment by fukajun** [comment]
- parse.com互換のAPI群を用意して徐々にparse.comから移行していくとかしたい
- facebookログインをparse.comから独立させる

**Comment by pandeiro245** [comment]
@fukajun 主要部分のAPI化完了しました！！

**Comment by pandeiro245** [comment]
Ad, Accesslog, Musicの部分は他の機能を実装しながら対応するので一旦close
