### ISSUE TITLE
プレイリスト機能

### ISSUE THREAD

**Issue by AkoNakayama** [pandeiro245/245cloud#172]
３ポモ確実！という時にノンストップでやるような感じの自動再生機能

**Comment by pandeiro245** [comment]
@AkoNakayama これ僕も欲しい！

**Comment by AkoNakayama** [comment]
優先度高めで
のってる時、ペース崩したくないなーってのがあります

**Comment by pandeiro245** [comment]
下記にて要件まとめます
https://ruffnote.com/pandeiro245/245cloud/issues/69
