### ISSUE TITLE
デスクトップ通知

### ISSUE THREAD

**Issue by tkrkt** [pandeiro245/245cloud#192]
これ使えばできると思います。

http://www.moongift.jp/2014/05/notify-js-html5%E3%81%AE%E3%83%87%E3%82%B9%E3%82%AF%E3%83%88%E3%83%83%E3%83%97%E9%80%9A%E7%9F%A5%E3%82%92%E6%89%8B%E8%BB%BD%E3%81%AB%E5%AE%9F%E8%A3%85%E3%81%A7%E3%81%8D%E3%82%8Bjavascript%E3%83%A9/

**Comment by pandeiro245** [comment]
#TODO 

* [ ] 西小倉のローカル（chrome）で通知ONにできない件を検証
* [ ] IEだとか未対応ブラウザの時は設定チェックボックスを非表示にする

**Comment by tkrkt** [comment]
ちなみに同じライブラリ使用の拙作pornodoroのデスクトップ通知は動きますかね？
http://pornodoro.tkrkt.com/

**Comment by pandeiro245** [comment]
![image](https://cloud.githubusercontent.com/assets/125965/13196669/3aa66c62-d818-11e5-9c78-b3d276f65832.png)

あと５分後にわかるはず？それにしてもエロいｗ

**Comment by pandeiro245** [comment]
@tkrkt push通知きませんでした。。。

**Comment by pandeiro245** [comment]
FJさんのMacアプリで実現済
