### ISSUE TITLE
マウスホバーで曲名全部わかるようにする

### ISSUE THREAD

**Issue by tkrkt** [pandeiro245/245cloud#193]
こういうの。title属性つけるだけで済みそう。
<img width="378" alt="245cloud" src="https://cloud.githubusercontent.com/assets/8198831/12220831/a799e998-b7c5-11e5-8d52-7382f55a57d6.png">

**Comment by pandeiro245** [comment]
@tkrkt ご対応ありございます！
http://getbootstrap.com/javascript/#static-tooltip
を使ってこんな感じで表示されるようにしてみました〜！

![image](https://cloud.githubusercontent.com/assets/125965/12327049/9d3441ce-bb17-11e5-9202-4f1e484613e2.png)

**Comment by pandeiro245** [comment]
本番反映済

**Comment by tkrkt** [comment]
きれい :+1:
