### ISSUE TITLE
タイマーのカウントダウン表示を画像ではなくwebfont（SVG）にする

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#218]
* [ ] 既存の画像をSVGにする
* [ ] SVGをwebfontにする

**Comment by pandeiro245** [comment]
0〜9の画像
https://ruffnote.com/attachments/24953
https://ruffnote.com/attachments/24954
https://ruffnote.com/attachments/24955
https://ruffnote.com/attachments/24956
https://ruffnote.com/attachments/24958
https://ruffnote.com/attachments/24959
https://ruffnote.com/attachments/24960
https://ruffnote.com/attachments/24961
https://ruffnote.com/attachments/24962
https://ruffnote.com/attachments/24963

**Comment by pandeiro245** [comment]
@fukajun SVGこんな感じでいかがでしょう？？
https://ruffnote.com/attachments/30111

**Comment by fukajun** [comment]
ありがとうございます。これでtimer-fontを作って作りますね。

**Comment by pandeiro245** [comment]
@fukajun ありがとうございます！fukajunさんをCollaboratorに追加させて頂きました。今後何かあればself assignお願いします！

**Comment by fukajun** [comment]
@pandeiro245 
![timerstart](https://cloud.githubusercontent.com/assets/505115/13195368/b64994fe-d7f3-11e5-865b-09c55ac79701.gif)

**Comment by fukajun** [comment]
ふむむ、そんなに目立たないと思ったけど似たようなWebFont使っても結構ちがいわかっちゃいますね。

**Comment by pandeiro245** [comment]
ちらつくよりましかも？？

**Comment by pandeiro245** [comment]
対応ありがとうございます！！

**Comment by fukajun** [comment]
https://www.google.com/fonts/specimen/Allan このフォント使ってみたんです

**Comment by fukajun** [comment]
refs #258

**Comment by pandeiro245** [comment]
@fukajun ありがとうございます！マージしました！
