### ISSUE TITLE
245cloud tools

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#247]
https://www.wantedly.com/company_tools
の個人版を作りたい

**Comment by tkrkt** [comment]
http://techwave.jp/archives/51754515.html
これ期待してたんですがサービス化しませんでしたね...

**Comment by pandeiro245** [comment]
@tkrkt ほほう。あれかな、５分休憩中だけみんなの装備が見られるようにすれば24分のモチベーションにもなるかな？？
