### ISSUE TITLE
Ruffnoteコンテンツをダウンロードして使う

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#267]
# メリット
- オフラインで開発できる
- 万が一ruffnote.comが落ちても245cloud.comに影響が出ない
- ruffnote.com側の負荷が減る
- JSレンダリングよりSEO的に有利
# TODO
- [ ] とりあえずつくる
- [ ] gem化する

**Comment by tkrkt** [comment]
SEO的なメリットもありますね。

**Comment by pandeiro245** [comment]
@tkrkt あざす！追記しました！

**Comment by pandeiro245** [comment]
https://github.com/pandeiro245/245cloud/pull/434
にてruffnote廃止する
