### ISSUE TITLE
mixcloudのworkload.music_keyの形式について考える

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#271]
# TODO
* [x] Workloadにrepair!メソッド追加（mixcloudの場合は冒頭スラッシュあり、の`URI.decode`した状態）
* [ ] `musics#show`のルーティングでは`/`は`_`に置換してアクセスさせる

# 前提

mixcloud以外は半角英数字のみで表記ゆれしないが、mixcloudのみ日本語が入ったりするので表記ゆれする

# 考察

・`URI.encode`した状態としない状態が混在すると別モノとして扱われてしまうので`URI.encode`した状態で統一する（そのためにはカラム長を増やす必要あり）
・`/`を`_`に置換することは不可逆（もともと`_`だったものも元に戻す時`/`に戻る）ので`_`ではなく何か他のものに置換する（何がいんだろう）

**Comment by pandeiro245** [comment]
@fukajun こちら、mixcloudのkeyは

http://245cloud.com/#mixcloud:/ib0ry/%E7%A7%81%E7%9A%84%E6%A4%8E%E5%90%8D%E6%9E%97%E6%AA%8E%E9%81%B8%E6%9B%B2%E9%9B%86-%E4%BD%9C%E6%A5%AD%E7%94%A8/

こんな感じでkeyの中にスラッシュが入っているんです。
今は
http://245cloud.com/musics/mixcloud/ib0ry/%E7%A7%81%E7%9A%84%E6%A4%8E%E5%90%8D%E6%9E%97%E6%AA%8E%E9%81%B8%E6%9B%B2%E9%9B%86-%E4%BD%9C%E6%A5%AD%E7%94%A8/
こういうURLは
https://github.com/pandeiro245/245cloud/blob/master/config/routes.rb#L19
こんな感じの暫定対応にしていますが
keyの中のスラッシュを何か別のものに置換して扱いたいなと考えています。

しかし、例えば`/`を`_`に置換してしまうと`hoge/fuga_poyo`みたいなkeyになっていた時、mixcloud APIが叩きたくて`_`を`/`に戻した時に`hoge/fuga/poyo`となってしまうんでダメだと思うんです。

`/`を何に変換するのが良いでしょう？

**Comment by fukajun** [comment]
:eyes:

**Comment by pandeiro245** [comment]
自分で再読してて心配になってきたｗ

`mixcloud:hoge/fuga_poyo`として扱っていたmusic_keyを
`mixcloud:hoge_fuga_poyo`にして変換するとmixcloudにいざリクエスト思った時にdecodeしようと思ったら`mixcloud:hoge/fuga/poyo`になってしまってそんなページないよって言われると思うんです

**Comment by fukajun** [comment]
思いつきですが、cookieなどに入れて値を`music_key`をそのままの状態で引き継ぐことはできないんでしょうか？

**Comment by pandeiro245** [comment]
@fukajun あーそっか、そのままで保存しておいて、
http://245cloud.com/musics/mixcloud/ib0ry/%E7%A7%81%E7%9A%84%E6%A4%8E%E5%90%8D%E6%9E%97%E6%AA%8E%E9%81%B8%E6%9B%B2%E9%9B%86-%E4%BD%9C%E6%A5%AD%E7%94%A8/
こういうURLの部分だけ`/`を`_`に置換して使う。でいい気がしてきた

**Comment by fukajun** [comment]
むむ、これで解決？（してる気がしない）

`javascript` でいうところの encodeURIComponent() を music_key のみにかけるという方法もあると思います。

**Comment by pandeiro245** [comment]
@fukajun あ、`/`って`%2F`なんですね。解決したっぽいです！対応します！
