### ISSUE TITLE
Youtube再生時のstart_secの設定について疑問

### ISSUE THREAD

**Issue by fukajun** [pandeiro245/245cloud#276]
動画の時間が24分を超えているものについては、最後の24分から始まるようになっているのはなぜなんでしょう？

**Comment by pandeiro245** [comment]
@fukajun これ、利用者から「そうすれば終わりがいい感じになる」って言われて実装したんですけど、その後 imazさんに「選べるようにしたい」っていう要望頂いてました！

**Comment by fukajun** [comment]
なるほど、終わりがいい感じになる必要があるとかは好みの問題なのでなんとも言えないですが、
選べるというのは確かに良いような気がしますね。
