### ISSUE TITLE
245cloud-app for mac 登場か？

### ISSUE THREAD

**Issue by fukajun** [pandeiro245/245cloud#284]
![monosnap 2016-03-06 16-01-55](https://cloud.githubusercontent.com/assets/505115/13552822/daa85fac-e3b4-11e5-8bfd-9e7e76f3f92f.png)

- わかったこと
  - そのままelectronで表示しようとすると、electron の node integrationを切らないといけない
  - electronで外部URLを表示すると、致命的なセキュリティーホールができるらしい↑のおかげでないかも
  - 単に表示しただけだと、 facebookのログインが切れる？
  - niconico動画はフラッシュとかの関係があるので再生できなさそう（未検証）

**Comment by pandeiro245** [comment]
！！

**Comment by fukajun** [comment]
electronでメニューバーアプリ作って表示してるだけですね。ちょっと一通り動作するか試してみます。

**Comment by fukajun** [comment]
![monosnap 2016-03-06 20-01-41](https://cloud.githubusercontent.com/assets/505115/13553742/4b7cd71e-e3d6-11e5-91ad-22ec84535aed.png)

**Comment by pandeiro245** [comment]
@fukajun 使いたい！！！

**Comment by fukajun** [comment]
次は、メニューバーに時間表示やります。

**Comment by pandeiro245** [comment]
> メニューバーに時間表示

欲しすぎるｗ

**Comment by fukajun** [comment]
![monosnap 2016-03-06 20-16-15](https://cloud.githubusercontent.com/assets/505115/13553804/4cac5d60-e3d8-11e5-9098-f53692968dc4.png)

**Comment by fukajun** [comment]
微妙にずれている

**Comment by pandeiro245** [comment]
表示されてるううううう。１秒のずれは大丈夫では？ｗ

**Comment by fukajun** [comment]
![monosnap 2016-03-06 20-18-28](https://cloud.githubusercontent.com/assets/505115/13553807/9c7a6ac6-e3d8-11e5-9560-74db8aa8f1de.png)

ほぼあわせました。

**Comment by pandeiro245** [comment]
:+1:

**Comment by fukajun** [comment]
はじまったときに `START!!!!!!` と　終わった時に `お疲れ様です` が通知でででるぅ

![1 electron helper 2016-03-06 20-33-15](https://cloud.githubusercontent.com/assets/505115/13553860/ae4c71a2-e3da-11e5-9752-1709ba8e690a.png)

**Comment by pandeiro245** [comment]
やばいいいいい

**Comment by fukajun** [comment]
とりあえず試し運転で1ぽも

**Comment by fukajun** [comment]
アイコンはビットコインアプリを作った時のものになってるので変えたい

**Comment by fukajun** [comment]
なんでこれ作るのにぽもしなかったんだろ？

**Comment by fukajun** [comment]
思い立って5ポモくらいでここまで来たので `electron` の簡単さヤバイ

**Comment by fukajun** [comment]
![1 tmux 2016-03-06 21-04-32](https://cloud.githubusercontent.com/assets/505115/13553992/2c7e2986-e3df-11e5-9d1b-08d56856fba7.png)

**Comment by pandeiro245** [comment]
イケてるー！そしてソースにはモザイクw

**Comment by fukajun** [comment]
会社のコードなんです(汗)

**Comment by fukajun** [comment]
チャットのコメント時に、`Refused to set unsafe header "User-Agent"` っていうエラーがでて
投稿できなかったwww

**Comment by pandeiro245** [comment]
245cloud APIつくらな！

**Comment by pandeiro245** [comment]
slackとかどうしてるんだろう？

**Comment by fukajun** [comment]
`electron` 側で、`User-Agent`ごまかせばいいのかな... <= あんまりよくないのだけど....

**Comment by pandeiro245** [comment]
245cloud側に
`headers['Access-Control-Allow-Origin'] = '*'`
追加してもだめかな？？

**Comment by fukajun** [comment]
parse.com 側なのでたぶんだめなんじゃないですかね？

**Comment by pandeiro245** [comment]
@fukajun 今コメントにはparse.com使ってないですよー！
ここ叩いてます https://github.com/pandeiro245/245cloud/blob/master/app/controllers/api/comments_controller.rb#L13

**Comment by fukajun** [comment]
おぉ？僕の勘違いですね。次のコメントのタイミングで再度デバッグしてみます。

**Comment by fukajun** [comment]
@pandeiro245 parse-min.js から発生はしていましたが、別のエラーっぽいです。
コメント投稿できることがわかりました。

**Comment by fukajun** [comment]
![monosnap 2016-03-06 21-37-52](https://cloud.githubusercontent.com/assets/505115/13554146/b05cef4a-e3e3-11e5-9100-26f668ef5b50.png)

**Comment by fukajun** [comment]
投稿できてました。

**Comment by pandeiro245** [comment]
イケてるー！電源はないですｗ

**Comment by fukajun** [comment]
wwwww

**Comment by fukajun** [comment]
アプリとしてビルドするとなぜか動かない現象が出た.... また調査して報告します。

**Comment by pandeiro245** [comment]
わくわく

**Comment by fukajun** [comment]
@pandeiro245 https://dl.dropboxusercontent.com/u/30627288/245cloud-darwin-x64.zip 
おまたせさまです。

**Comment by pandeiro245** [comment]
！！！！

**Comment by fukajun** [comment]
アイコンを作る時間がなかった等々あるけどもクローズドβ的な扱いです。

**Comment by fukajun** [comment]
あれ....バグってる

**Comment by pandeiro245** [comment]
![image](https://cloud.githubusercontent.com/assets/125965/13603461/b1cb9068-e580-11e5-8d89-89467c4e8c93.png)

ふむふむ

**Comment by fukajun** [comment]
これになる時とならない時があるんですよねー調査中

**Comment by fukajun** [comment]
何回か試してると行ける時がある
Electronクッキーサポート入れるか

**Comment by fukajun** [comment]
@pandeiro245 新しいのビルドしてみましたどうでしょう？

**Comment by fukajun** [comment]
すみません、まだアップロード出来てなかった

**Comment by fukajun** [comment]
アップロード完了しました。

**Comment by pandeiro245** [comment]
https://dl.dropboxusercontent.com/u/30627288/245cloud-darwin-x64.zip 

これであってます？
今回も同じ挙動のようです。。。

![image](https://cloud.githubusercontent.com/assets/125965/13622226/9d36ef20-e5e0-11e5-9b6b-9b316eb71289.png)

**Comment by pandeiro245** [comment]
@fukajun あとこれ、無限に増えていきそうな気がするのですがアプリ削除の方法ってわかります？？

**Comment by fukajun** [comment]
アプリってどのことを言ってますか？ :bow:

**Comment by pandeiro245** [comment]
@fukajun 
![image](https://cloud.githubusercontent.com/assets/125965/13626985/311dc7ee-e60a-11e5-80da-f81a72e1df6a.png)

こんな感じで終了させられればよい？？

**Comment by fukajun** [comment]
なるほど、　開いた状態で cmd + Q で終了できます。
後ほど、終了の機能つけます。

**Comment by pandeiro245** [comment]
@fukajun cmd + Q いけました！ありがとうございます！

**Comment by fukajun** [comment]
facebookログインをアプリからなんとかする方法を検討中
一度facebookログインした人は、`token` とかAPPに設定して認証できるようにならないのかなぁと思ってます。

**Comment by fukajun** [comment]
先にアプリ自体を済ますとかすればいいのかなーーーうーん

**Comment by fukajun** [comment]
でた　https://github.com/fukajun/245cloud-app
