### ISSUE TITLE
通常の時のヘッダーのイメージと、休憩中のイメージについて

### ISSUE THREAD

**Issue by fukajun** [pandeiro245/245cloud#296]
ソースコードのどの辺で表示させてるんですかねぇー。探したけどわか、なからなかったので知りたいです。よろしくお願いします。

**Comment by pandeiro245** [comment]
@fukajun https://github.com/pandeiro245/245cloud/blob/master/app/assets/javascripts/main.coffee#L34 ここで
https://ruffnote.com/pandeiro245/245cloud/23854
これを表示している感じです！

**Comment by fukajun** [comment]
これって、Ruffnoteに入っているコンテンツを表示している感じですか？
表示をRuffnoteから管理できるような思想なんですかね？

**Comment by pandeiro245** [comment]
@fukajun ですです、非エンジニアでもGitHubを解さず修正できるイメージ。
