### ISSUE TITLE
245cloud for mac のダウンロードリンクを貼りたい

### ISSUE THREAD

**Issue by fukajun** [pandeiro245/245cloud#301]
貼ってくれたりするのかな.....

**Comment by pandeiro245** [comment]
@fukajun そりゃもちろん！

**Comment by pandeiro245** [comment]
@fukajun ここに反映依頼ってできます？それかここのコメントに指示でもOKす
https://ruffnote.com/pandeiro245/245cloud

**Comment by fukajun** [comment]
反映依頼します。

**Comment by pandeiro245** [comment]
@fukajun とりあえずこんな感じで貼ってみました！
https://ruffnote.com/pandeiro245/245cloud/18004

**Comment by pandeiro245** [comment]
ずっとトップに貼ってるので一旦closeします！
![image](https://user-images.githubusercontent.com/125965/128593017-2fb4808c-677c-4a94-b292-de0defcc39b2.png)
