### ISSUE TITLE
共有お絵かき

### ISSUE THREAD

**Issue by tkrkt** [pandeiro245/245cloud#312]
マーキーって聞いて共有お絵かき掲示板かな？って思ったら
MARQUEEタグなるものがあるのね。

（試してないけど）こういうの使ってお絵かきで遊べるかも。

https://awwapp.com/
https://awwapp.com/docs/plugin/quickstart/

**Comment by pandeiro245** [comment]
やりたーい！！

**Comment by pandeiro245** [comment]
そしてアサインしましたｗ

**Comment by tkrkt** [comment]
他にも埋め込み向けの共有お絵かきのサービスってありそうで見当たらない...
確かにサーバ負荷高そうだけど。
