### ISSUE TITLE
IBM Bluemixを使って無料でホスティングする案

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#322]
そもそも無料枠でもRuby使えるのかすらわかっていない…。

https://console.ng.bluemix.net/pricing/
http://qiita.com/akameco/items/39a55635ceb0ba185b7f

**Comment by tkrkt** [comment]
1アプリだけならherokuという手も。

http://qiita.com/tomomichi/items/7904dfcdabb7acc8a286

**Comment by pandeiro245** [comment]
やるとしたらFirebase Hostingってことになった
