### ISSUE TITLE
ニコニコ動画が再生できなくなっている

### ISSUE THREAD

**Issue by kobake** [pandeiro245/245cloud#338]
ニコニコ動画が再生できなくなってます（？）

Chrome で要素検索してみたら、何故か embed.nicovideo.jp の iframe が head 内に埋まっていたので、これを body 側に移してあげれば良さそうです。
ニコニコのスクリプト側の問題な気もしますが、245cloud 側で対応するとしたら、Nicovideo の

```
    script = document.createElement('script')
    script.src = "http://ext.nicovideo.jp/thumb_watch/#{sm_id}"
    $dom.append(script)
```

の直後に

```
setTimeout(function(){
    $('head iframe').each(function(){
        var src = $(this).attr('src');
        if(src && src.match(/http:\/\/embed.nicovideo/)){
            $('#playing').append($(this));
        }
    });
}, 5000); // ここはちょっとずるをしている。もっと厳密なハンドリングの仕方もあるはず。
```

みたいな処理を入れれば一応再生可能にはなるかと思います。（手元の Developer Tools では動作確認済み）

プルリク送りたい気持ちもあるのですが coffee よくわからないので…すいません

**Comment by kobake** [comment]
ちゃんとした修正方法あったのでプルリク投げました↑

**Comment by pandeiro245** [comment]
@kobake forkしてからPRまで爆速ｗ確認します！ありがとうございます！！

**Comment by kobake** [comment]
むふふ :) よろしくお願いします～

**Comment by pandeiro245** [comment]
@kobake マージして本番環境での正常動作を確認しました。ありがとうございました！！

**Comment by kobake** [comment]
確認&適用あざます〜〜
