### ISSUE TITLE
[リファクタリング] 上部の画像のハードコーディング & 省スペース化

### ISSUE THREAD

**Issue by fukajun** [pandeiro245/245cloud#373]
- 上部のでかい画像が変わったことないのでハードコーディングで良さそう
- 休憩中の画像がappのほうで表示するとはみ出してるのでちゃんとレスポンシブ化

**Comment by pandeiro245** [comment]
たしかに

**Comment by pandeiro245** [comment]
https://github.com/pandeiro245/245cloud/pull/442
にて対応済
