### ISSUE TITLE
交換日記入力中に5分のタイムオーバーで落ちた

### ISSUE THREAD

**Issue by harada4atsushi** [pandeiro245/245cloud#4]
忘れないようにissue上げてみました！
問題ないですか？

ちなみにissueとかpull reqは英語推奨な文化です？

スクショ
![2014-07-24 23 09 37](https://cloud.githubusercontent.com/assets/1818925/3689015/36fdba68-133c-11e4-9ff9-82c9ec22bb2a.png)

**Comment by pandeiro245** [comment]
@harada4atsushi 
こちら、もう大丈夫だと思いますが再発したら教えてください。一旦Closeさせて頂きます...！

**Comment by harada4atsushi** [comment]
りょうかいっす。最近は出てないですね！
