### ISSUE TITLE
TODO機能

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#96]
- [ ] それぞれのTODOに対して何ポモかかるか見積れる
- [ ] 上記と1日あたりの平均ポモ数を計算してpivotal trackerみたいに自動的に未来スケジュールが組まれる
- [ ] 実際のポモ（Workloadモデル）とTODOをhas_manyで紐付ける
- [x] はらぱんさんとペアプロする日程を調整する

**Comment by harada4atsushi** [comment]
ペアプロ予定入ってるww

**Comment by tkrkt** [comment]
ToDo+Pomodoroというと、Pomelloが割と優秀です。Trello連携。さんこうまでー
https://chrome.google.com/webstore/detail/pomello/ahjnfakocpfoocnncbgmondnnnlfjide

**Comment by pandeiro245** [comment]
Googleログインしようとしたら友達の情報まで教えて言われるｗ

![image](https://cloud.githubusercontent.com/assets/125965/13196731/67b6f9ae-d81a-11e5-8f55-70317a4ea51e.png)
